apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
      - name: capstone-project
        image: tamermohamed/udacity_capstone:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
